version: "3.9"

services:
  inventory:
    container_name: inventory
    build:
      context: .
      dockerfile: Dockerfile
    command: python start.py
    ports:
      - "8001:8000"
    restart: unless-stopped
    environment:
      APP_ENV: production
      MONGO_URI: "your-mongodb-uri"
