version: "3.9"

services:
  inventory:
    container_name: inventory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_PORT: 8001
    volumes:
      # Persist logs in /var/lib/inventory-logs on the host
      - inventory_logs:/app/logs
      # Optional: mount current code for dev hot-reload
      # - .:/app

volumes:
  inventory_logs:
    driver: local
