version: "3.9"

services:
  inventory:
    container_name: inventory
    build:
      context: .
      dockerfile: Dockerfile
    command: python start.py
    ports:
      - "8001:8000"  # Host:Container
    restart: unless-stopped
    environment:
      # Add your environment variables here
      APP_ENV: production

    volumes:
      # - .:/app  # Optional: only for local dev, remove in production
