name: Deploy to Remote Server with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Ensure Docker & Compose are installed
            sudo apt update -y
            sudo apt install -y docker.io docker-compose-plugin

            # Enable Docker to start on boot
            sudo systemctl enable --now docker

            # Go to the project folder where docker-compose.yml is already present
            cd ~/inventory-app

            # Pull latest changes
            git reset --hard
            git pull origin main

            # Rebuild and restart
            docker compose down
            docker compose up -d --build
