name: Deploy to Remote Server with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop & remove any existing inventory container
            docker rm -f inventory || true

            # Remove old project folder completely
            rm -rf ~/inventory
            mkdir -p ~/inventory
            cd ~/inventory

            # Initialize repo if missing
            git init
            git remote add origin git@github.com:${{ github.repository }}
            git fetch origin
            git checkout -b main origin/main

            # Build & run
            docker compose up -d --build
