name: Deploy to Remote Server with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create folder if it doesn't exist
            mkdir -p ~/inventory
            cd ~/inventory

            # If not a git repo, initialize and add origin
            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:${{ github.repository }}
              git fetch origin
              git checkout -b main origin/main
            else
              git reset --hard
              git pull origin main
            fi

            # Build & restart the container
            docker compose down || true
            docker compose up -d --build
