name: Deploy to Remote Server with Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on remote server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Docker & Compose if missing
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io docker-compose-plugin
              sudo systemctl enable --now docker
            fi

            # Pull or clone repo
            if [ ! -d ~/inventory-app ]; then
              git clone git@github.com:${{ github.repository }} ~/inventory-app
            fi

            cd ~/inventory-app
            git reset --hard
            git pull origin main

            # Restart container with latest code
            docker compose down
            docker compose up -d --build
