name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH and Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Copy project to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/home/${{ secrets.SSH_USER }}/inventory"
          strip_components: 0  # keep directory structure

      - name: SSH into remote server and run Docker commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/inventory
            # Stop and remove existing inventory container
            docker stop inventory || true
            docker rm inventory || true
            # Build new image
            docker build -t inventory .
            # Create network if it doesn't exist
            docker network create inventory-network || true
            # Start new container
            docker run -d --name inventory -p 8001:8001 \
              --network inventory-network \
              -e MONGODB_HOST=mongodb \
              -e MONGODB_PORT=27017 \
              -e MONGODB_DATABASE=inventory \
              -e MONGODB_USERNAME=imaad \
              -e MONGODB_PASSWORD=Ertdfgxc \
              inventory
            # Show running containers
            docker ps
